development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mapapp_development
  pool: 5
  username: root
  password: ll
  #socket: /var/run/mysqld/mysqld.sock
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mapapp_test
  pool: 5
  username: root
  password: ll
  #socket: /var/run/mysqld/mysqld.sock
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mapapp_production
  pool: 5
  username: root
  password: ll
  #socket: /var/run/mysqld/mysqld.sock
  socket: /tmp/mysql.sock